### ISSUE TITLE
Building native code

### ISSUE THREAD

**Issue by computerlyrik** [mattjlewis/pigpioj#1]
Hi! 

I wonder how you build the native part of the project.
I am trying to cover native and java code completely in a maven lifecycle.

If you are interested, i will make a pull request after finding out what the compiler and linker arguments are.

Can you provide a small Makefile oder gcc calls?

Re-Packaging allows even to not commit libpigpio.so into lib/ directory of the java project for packaging. (I tested this locally) - if you are interested.

**Comment by computerlyrik** [comment]
Found the Makefile - doing some work now. 

May i tell you when i finished the coding (mainly pom.xmls) for a review?

**Comment by mattjlewis** [comment]
Absolutely. 

Regards,
Matt
