### ISSUE TITLE
Pigpioj not working on Raspberry PI 4

### ISSUE THREAD

**Issue by NoelVaes** [mattjlewis/pigpioj#12]
I tried the example on Raspberry PI 4.

**Base image**: 
https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2020-08-24/2020-08-20-raspios-buster-arm64-lite.zip

**PIGPIO installed**:

```
sudo apt-get update
sudo apt-get install pigpio

```
**Running example**:

Code:

```
      int gpio = 4;
      try (PigpioInterface pigpio_impl = PigpioJ.getImplementation()) {
         pigpio_impl.setMode(gpio, PigpioConstants.MODE_PI_INPUT);
         pigpio_impl.read(4);
      }

```
Result:

```
Error in gpioInitialise: -1
Exception in thread "main" java.lang.RuntimeException: Error initialising pigpio: -1
        at uk.pigpioj.PigpioJNI.<init>(PigpioJNI.java:54)
        at uk.pigpioj.PigpioJ.getImplementation(PigpioJ.java:29)
        at com.vangenechten.test.diozero.DiozeroTest.main(DiozeroTest.java:22)

```

**Comment by mattjlewis** [comment]
Quick questions:
1. Are you running as root?
2. Is the pigpiod daemon process running?

**Comment by NoelVaes** [comment]
Thanks for you instant reply.

Yes I'm running the Java application as root and the pigpiod is running. I use OpenJDK11.

```
root@raspberrypi:/home/pi# sudo systemctl status pigpiod
● pigpiod.service - Daemon required to control GPIO pins via pigpio
   Loaded: loaded (/lib/systemd/system/pigpiod.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-01-21 09:30:12 CET; 1h 35min ago
  Process: 617 ExecStart=/usr/bin/pigpiod -l (code=exited, status=0/SUCCESS)
 Main PID: 618 (pigpiod)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/pigpiod.service
           └─618 /usr/bin/pigpiod -l
```


```
root@raspberrypi:/home/pi# java -jar DiozeroTest.jar
Diozero Test
Error in gpioInitialise: -1
Exception in thread "main" java.lang.RuntimeException: Error initialising pigpio: -1
        at uk.pigpioj.PigpioJNI.<init>(PigpioJNI.java:54)
        at uk.pigpioj.PigpioJ.getImplementation(PigpioJ.java:29)
        at com.vangenechten.test.diozero.DiozeroTest.main(DiozeroTest.java:22)
```

**Comment by mattjlewis** [comment]
Can you please try again with the pigpiod daemon process stopped.

**Comment by NoelVaes** [comment]
Now it works. 

It seems that pigpiod has to be started and stopped once. Is this correct?

After a reboot and pipgpiod disabled it keeps working now.

Is there an explanation?

**Comment by mattjlewis** [comment]
I've updated the pigpioj readme to state that the pigpiod daemon must be stopped for JNI mode to work - disabling it is even better to make sure it doesn't auto-start on a reboot, I can also add that to the docs.

It shouldn't need to be started and then stopped once, I've not encountered that before.

Good that it is working!

**Comment by NoelVaes** [comment]
Thanks for your help!
