### ISSUE TITLE
i2s driver/servo function clash - need access to gpioCfgClock?

### ISSUE THREAD

**Issue by salk31** [mattjlewis/pigpioj#15]
Hello,

I think I've hit this problem https://github.com/joan2937/pigpio/issues/87.

I had servo control working fine until I enabled "dtoverlay=hifiberry-dac" in config.txt then the servos just started twitching. I've not checked with a scope but looked to me like the wrong frequency/width.

The linked issue suggests I need to call gpioCfgClock to switch the DMA function from using the PCM to the PWM. I've looked and searched but I don't think pigpioj exposes this yet? Would it be a sensible addition? If so would you welcome pull requests?

Cheers

Sam

**Comment by salk31** [comment]
Wow. Fixed before I returned to this project to see if I could fix it ;) Just tested and I have sound and servo control. Many thanks.

**Comment by mattjlewis** [comment]
Brilliant, good to know - was a trivial feature to add. I'll release once I've added a note in the README. Glad you find the library useful.
