### ISSUE TITLE
signal 11 issue

### ISSUE THREAD

**Issue by petercwallis** [mattjlewis/pigpioj#4]
First thanks Matthew for making this available.  I am trying to use pigpio with java to drive my lego robot.  It has the pi camera attached and I get signal 11 whenever I have the camera working.  I have seen your reference to JNI signal handling:
https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/signals003.html#CIHFCAIG
And have come across the "fix" that joan et al have for this issue:
https://github.com/joan2937/pigpio/pull/164

I have no idea how to integrate "1<<10" with this code.  I am "expert" at java but my C is 20+ years old.  A pointer or two and I'll give it a go; am happy to test...

P

**Comment by petercwallis** [comment]
Okay I have a fix and was trying to make a PR but I have 15minutes which it not long enough to figure out how to make a branch from the gui and then spend another 15minutes sorting a PR.  Git hub needs better doc !!!

in the file uk_pigpioj_PigpioGpio.c

before the call to gpioInitiaise() at line 75

added a call to:
rc = gpioCfgSetInternals(1<<10);
if( rc < 0 ) {
	fprintf(stderr,"Error disabling signal handling: %d\n",rc);
	return -1;
}

**Comment by mattjlewis** [comment]
Excellent, thank you. I will incorporate.
