### ISSUE TITLE
Remove message spamming console

### ISSUE THREAD

**Issue by chuckb** [mattjlewis/pigpioj#5]
I am using your library to read waveforms from a Pi GPIO pin, and doing so with pigpiod. The following line is spamming the console with messages. Can you put a guard around it so it can be suppressed?

https://github.com/mattjlewis/pigpioj/blob/f6cb6cdf684e28b4ef3294e509d0d228c3ec3ee0/pigpioj-java/src/main/java/uk/pigpioj/PigpioSocket.java#L325

**Comment by mattjlewis** [comment]
This should now be resolved - pushed version 2.3.

**Comment by chuckb** [comment]
Wow, that was fast. Thanks!

Quick question...I have a servo with a one-wire feedback encoder which pulses a waveform every ~1.1 millisecond. The duty cycle indicates the position of the servo. I have been using pigpiod for sending signals to the Pi over the network so I don't have to push my code (and this works remarkably well for controlling the servos - pigpiod timing set to default of 5 microsecond samples and 120 millisecond buffer). I can't seem to get the feedback timing measurements to work right.

I have implemented a class which extends DigitalInputDevice and implements InputEventListener<DigitalInputEvent>. In the valueChanged method, I implemented a simple state machine which looks for a rising edge, measures the high time at the next falling edge, and then measures the low time at the next rising edge. I check to see if my low + high timing is within a 1000000 to 1200000 nanosecond range and it never is.

I did scope the servo feedback wire to confirm that the pulses are as expected.

Recognizing that my program is only going to get the events in 120 millisecond bursts, I still would expect good, albeit delayed, timings.

So, here is my question: Do the valueChanged events get fired sequentially and in the order of arrival?

Thanks for a great lib.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by chuckb** [comment]
And one more question...is the nanotime on the event from the Pi daemon?

**Comment by mattjlewis** [comment]
Apologies for the very long delay (!). The nanotime is generated within pigpioj, unfortunately pigpio doesn't generate that. The valueChanged events should be entirely sequential and in order.

**Comment by moroff** [comment]
Using the latest version (2.5.3) I still get this message

_INFORMATION: Waiting for events
changed_level_mask: 269484047
Jan 05, 2021 8:04:05 PM info.moroff.raspi.raincontrol.diagnostics.Tools$1 callback
INFORMATION: Got triggered event on pin 20 with value true
changed_level_mask: 1048576_

**Comment by mattjlewis** [comment]
Ah, missed one. Have now removed and will push 2.5.4 later today.

**Comment by mattjlewis** [comment]
Done.

**Comment by moroff** [comment]
Thanks for the quick reply and action, now it works perfectly for me. 

You might consider using java.util.logging instead of System.out.println. I'm not a fan of java.util.logging (usually log4j is my choice) but on the raspi I want to avoid extra dependencies.

If you like and agree I can make this changes and provide a pull request.

**Comment by mattjlewis** [comment]
That would be great if you could add JDK logging. I use tinylog in diozero as I don't like JDK logging, but have deliberately not used any logging frameworks in pigpioj to avoid dependencies for this library As you say, it is nice to avoid extra dependencies.
