### ISSUE TITLE
Instructions how to use?

### ISSUE THREAD

**Issue by birgersp** [mattjlewis/pigpioj#7]
I would like to see the README include some instructions on how to use this in other projects. How do you build `pigpioj-native`, for example?

**Comment by mattjlewis** [comment]
I will create a simple README.

**Comment by mattjlewis** [comment]
This ok? https://github.com/mattjlewis/pigpioj

**Comment by birgersp** [comment]
Thanks @mattjlewis, you're doing a great job with this lib!
