### ISSUE TITLE
pigpoij vs diozero

### ISSUE THREAD

**Issue by moroff** [mattjlewis/pigpioj#9]
Can I use **pigpioj** in my project or should I use **diozero**. I actually like **pigpioj** as there is no much abstraction to the underlying native libraries, but currently I'm struggling because the jni library was not loaded

`
Error loading library from classpath, trying System.loadLibrary: java.lang.UnsatisfiedLinkError: /tmp/libpigpioj-arm1488516877227514560.so: libpigpio.so.1: Kann die Shared-Object-Datei nicht ?ffnen: Datei oder Verzeichnis nicht gefunden
Error loading pigpioj library from system library path: java.lang.UnsatisfiedLinkError: no pigpioj in java.library.path
java.lang.UnsatisfiedLinkError: no pigpioj in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at uk.pigpioj.PigpioJNI.initialise(PigpioJNI.java:34)
	at uk.pigpioj.PigpioJNI.<init>(PigpioJNI.java:52)
	at uk.pigpioj.PigpioJ.getImplementation(PigpioJ.java:29)
`

My commandline is
`
pi@raspberrypi:~/artifacts$ java -cp lib/raincontrol-base-0.1.0-SNAPSHOT.jar:lib/netty-all-4.1.54.Final.jar:lib/pigpioj-java-2.5.3.jar -jar raincontrol-diagnostics-0.1.0-SNAPSHOT.jar --inputTest
`

**Comment by moroff** [comment]
Installing pigpio solves the first problem

_sudo apt-get update
sudo apt-get install pigpio python-pigpio python3-pigpio_

but after that I get the next problem
`
Error in gpioInitialise: -1
`
That's native code, how can I debug?

**Comment by mattjlewis** [comment]
Hmm, could be a bug in pigpioj, I'll take a look. What Raspberry Pi model are you using?

**Comment by moroff** [comment]
4B with 8GB

**Comment by mattjlewis** [comment]
Can you check if you are running the pigpiod daemon process please.
`systemctl status pigpiod`

**Comment by moroff** [comment]
pi@raspberrypi:~$ systemctl status pigpiod
   pigpiod.service - Daemon required to control GPIO pins via pigpio
   Loaded: loaded (/lib/systemd/system/pigpiod.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

**Comment by moroff** [comment]
Maybe a reboot after installing

**Comment by mattjlewis** [comment]
I'll try on my Pi 4B tomorrow. pigpioj has 2 modes of operation - JNI and sockets. JNI is the default and I believe requires the pigpiod process to be inactive. The Sockets mode is enabled by setting the command line property "PIGPIOD_HOST" to the hostname of the Pi that is running pigpiod, e.g. `java -DPIGPIOD_HOST=localhost`.
If the JNI mode still doesn't work after a reboot, you could try the sockets mode by starting the pigpiod daemon process with:
```
sudo systemctl start pigpiod
```

**Comment by moroff** [comment]
Thanks for today ;-). This works, but unable to connect. I will check tomorrow
Exception in thread "main" io.netty.channel.AbstractChannel$AnnotatedConnectException: Verbindungsaufbau abgelehnt: localhost/127.0.0.1:8888
Caused by: java.net.ConnectException: Verbindungsaufbau abgelehnt
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)

**Comment by mattjlewis** [comment]
Note that in JNI mode pigpio requires you to run as root user. I've just tested locally with 1.0.0 on my Pi4 and it works ok.
```
> sudo java -Dtinylog.level=info -Dtinylog.level@com.diozero=info -cp diozero-sampleapps-1.0.0.jar:diozero-provider-pigpio-1.0.0.jar com.diozero.sampleapps.LEDTest 12
11:04:58.507 [main] INFO com.diozero.sampleapps.LEDTest.test - On
11:04:59.564 [main] INFO com.diozero.sampleapps.LEDTest.test - Off
11:05:00.566 [main] INFO com.diozero.sampleapps.LEDTest.test - Toggle
11:05:01.567 [main] INFO com.diozero.sampleapps.LEDTest.test - Toggle
11:05:02.569 [main] INFO com.diozero.sampleapps.LEDTest.test - Blink 5 times
11:05:07.572 [main] INFO com.diozero.sampleapps.LEDTest.test - Done
```
I can confirm that I get `Error in gpioInitialise: -1` if the pigpiod daemon process is running and I try to run the same command above using JNI mode.
I can also confirm that sockets mode also works:
```
> java -Dtinylog.level=info -Dtinylog.level@com.diozero=info -DPIGPIOD_HOST=localhost -cp diozero-sampleapps-1.0.0.jar:diozero-provider-pigpio-1.0.0.jar com.diozero.sampleapps.LEDTest 12
11:06:16.088 [main] INFO com.diozero.sampleapps.LEDTest.test - On
11:06:17.168 [main] INFO com.diozero.sampleapps.LEDTest.test - Off
11:06:18.171 [main] INFO com.diozero.sampleapps.LEDTest.test - Toggle
11:06:19.176 [main] INFO com.diozero.sampleapps.LEDTest.test - Toggle
11:06:20.180 [main] INFO com.diozero.sampleapps.LEDTest.test - Blink 5 times
11:06:25.198 [main] INFO com.diozero.sampleapps.LEDTest.test - Done
```
The beauty of the sockets mode is that if you enable remote sockets you can run your application from any device on your local network. This is extremely useful when developing on a laptop / desktop. You can check if remote sockets mode is enabled by inspecting `/etc/systemd/system/pigpiod.service.d/public.conf` - the daemon process is limited to local sockets if the ExecStart command has the "-l" parameter, i.e. `ExecStart=/usr/bin/pigpiod -l`.
If it does and you want to enable remote sockets, simply change to `ExecStart=/usr/bin/pigpiod`.

**Comment by moroff** [comment]
Thanks for supporting. Running as root with JNI solves my problem. In your example above you are using diozero-provider-pigpio-1.0.0.jar, I used pigpioj-java-2.5.3.jar, which one do you recommend? 

I just don't want to change again, I started my project with pi4j but as I have problems with the raspi4 I am looking for something better supported.

**Comment by mattjlewis** [comment]
It depends on whether you want the portability, flexibility and abstraction of diozero vs. the raw features of pigpioj. diozero is my main driver for developing pigpioj.

**Comment by mattjlewis** [comment]
Both are equally supported, my recommendation would be diozero.

**Comment by moroff** [comment]
Is pigpioj the base of diozero?

**Comment by mattjlewis** [comment]
diozero uses a Service Provider mechanism (similar to JDBC) to support different implementations under the covers. pigpioj is one such provider that is exposed via the diozero-provider-pigpgio adapter layer that you can see in my example above. diozero comes with its own builtin provider that is completely portable across devices but lacks a few features and optimisations that pigpio can provide.

**Comment by moroff** [comment]
Thanks for this explanation
